# Generated by Django 5.1.4 on 2025-01-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.pedido'),
        ),
    ]
