# Generated by Django 5.1.4 on 2025-01-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_itenspedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='finalizacao',
            field=models.BooleanField(default=False),
        ),
    ]
