# Generated by Django 5.1.4 on 2025-01-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_pedido_finalizado_pedido_finalizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='finalizacao',
            new_name='finalizado',
        ),
    ]
